
# Model arguments
# Qwen/Qwen2.5-1.5B Qwen/Qwen2.5-0.5B
model_name_or_path: Qwen/Qwen2.5-1.5B
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_name: xiaodongguaAIGC/X-R1-750
dataset_configs:
- train
num_processes: 1

# GRPO trainer config
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.7
do_eval: no
eval_strategy: "no"
eval_steps: 10
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
log_level: info
logging_steps: 10
logging_strategy: steps
lr_scheduler_type: cosine
learning_rate: 3.0e-06
max_prompt_length: 256
num_generations: 16
max_completion_length: 1024
max_steps: -1
num_train_epochs: 3
output_dir: ./chkp_dir/qwn1.5_0213
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 2
push_to_hub: False
save_strategy: "epoch"
seed: 42
warmup_ratio: 0.1